version: "3"

services:
  bitcoind:
    build: ./docker/bitcoind
    container_name: bitcoind
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./docker/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
    ports:
      - "8332:8332"
      - "8333:8333"

  indexer:
    build: ./docker/indexer
    container_name: indexer
    working_dir: /app
    volumes:
      - ./srcs/indexer:/app
    ports:
      - "4000:4000"
    restart: unless-stopped