version: "3"

services:
  bitcoind:
    build: ./docker/bitcoind
    container_name: bitcoind
    restart: unless-stopped
    volumes:
      - ./data/bitcoind:/data
      - ./docker/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
    ports:
      - "8332:8332"
      - "8333:8333"

  indexer:
    build: ./docker/indexer
    container_name: indexer
    working_dir: /app
    volumes:
      - ./srcs/indexer:/app
    restart: unless-stopped

  backend:
    build: ./docker/backend
    container_name: backend
    working_dir: /app
    volumes:
      - ./srcs/backend:/app
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build: ./docker/frontend
    container_name: frontend
    working_dir: /app
    volumes:
      - ./srcs/frontend:/app
    ports:
      - "5173:8000"
    restart: unless-stopped

  mongodb:
    build: ./docker/mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    restart: unless-stopped